package com.petruciostech.conversordemoeda.util.tools

const val TAG_ERROR_RESPONSE = "##ErrorResponse##"
const val TAG_SUCCESS_RESPONSE = "##SucessResponse##"
const val TEXT_ERROR_RESPONSE = "API response FAILED"
const val TEXT_SUCCESS_RESPONSE = "API response SUCESS"
const val TAG_ERROR_THREAD_PRICE = "##ERROR_PRICE##"
const val TEXT_ERROR_THREAD_PRICE = "Algo deu errado na requisição do preço do dollar!"
const val TAG_SUCCESS_THREAD_PRICE = "##INFO_PRICE##"
const val TEXT_SUCCESS_THREAD_PRICE = "Requisição feita com sucesso!"
const val TAG_SUCCESS_THREAD_LIST = "##SUCCESS_LIST##"
const val TEXT_SUCCESS_THREAD_LIST = "Requisição da lista feita com sucess"
const val TAG_ERROR_THREAD_LIST = "##ERROR_LIST##"
const val TEXT_ERROR_THREAD_LIST = "Requisição da lista teve erro"
const val SHARED_PREF_KEY = "##Shared_key##"
const val SHARED_BOOLEAN_ONE_KEY = "##Idioma_escolhido1##"
const val SHARED_BOOLEAN_TWO_KEY = "##Idioma_escolhido2##"
const val SHARED_CODE_STRING_KEY_ONE = "##CodeCurrencyOne##"
const val SHARED_CODE_STRING_KEY_TWO = "##CodeCurrencyTwo##"
const val INTENT_EXTRA_NUMBER_BUTTON = "##Button_Choise##"
const val SHARED_BOOLEAN_INITORNOT = "##App_init##"